spring.application.name=shop-backend

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

admin.setup.email=${ADMIN_EMAIL:admin@shop.com}
admin.setup.password=${ADMIN_PASSWORD:admin123}
admin.setup.name=${ADMIN_NAME:Super Admin}

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=ecommerce_db